version: "3.0"
services:
    portainer:
        image: portainer/portainer-ce:2.5.1
        ports:
            - "9000:9000"
            - "8000:8000"
        volumes:
            - ./portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
    registry:
        image: registry:2
        ports:
            - "5000:5000"
        volumes:
            - ./registry_data:/var/lib/registry
            - ./registry_auth:/auth
        environment:
            - "REGISTRY_AUTH=htpasswd"
            - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
            - "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd"