version: "3.0"
services:
    portainer:
        image: portainer/portainer-ce:2.5.1
        ports:
            - "9000:9000"
            - "8000:8000"
        volumes:
            - ./portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock